<a href="https://colab.research.google.com/github/alkarps/GB.Linear-Algebra/blob/hw02/hw02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

## Матрицы и матричные операции. Часть 1

### Задание №1

Установите, какие произведения матриц $AB$ и $BA$ определены, и найдите размерности полученных матриц:

   а) $A$ — матрица $4\times 2$, $B$ — матрица $4\times 2$;
    
   б) $A$ — матрица $2\times 5$, $B$ — матрица $5\times 3$;
    
   в) $A$ — матрица $8\times 3$, $B$ — матрица $3\times 8$;
    
   г) $A$ — квадратная матрица $4\times 4$, $B$ — квадратная матрица $4\times 4$.

а) Произведение $AB$ и $BA$, где матрица $A$ размерности $4\times 2$ и матрица $B$ размерности $4\times 2$ - не определены;
    
   б) Матрица $C$, являющаяся произведением $AB$, где матрица $A$ размерности $2\times 5$ и матрица $B$ $5\times 3$, определена и имеет размерность $2\times 3$. Матрица $BA$ неопределна;
    
   в) Для матриц $A$ размерности $8\times 3$ и $B$ размерности $3\times 8$ определены матрицы произведения $AB$ размерности $8\times8$ и $BA$ размерности $3\times3$;
    
   г) Так как у обоех квадратных матриц $A$ и $B$ одинаковая размерность $4\times 4$ произведения $AB$ и $BA$ таких матриц определено и будет такой же размерности,что и исходные матрицы.

### Задание №2

Найдите сумму и произведение матриц $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$

$A+B = \begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix} + \begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix} = \begin{pmatrix}
1+4 & -2+(-1)\\ 
3+0 & 0+5
\end{pmatrix} = \begin{pmatrix}
5 & -3\\ 
3 & 5
\end{pmatrix}$

In [2]:
a = np.array([[1,-2],[3,0]])
b = np.array([[4,-1],[0,5]])
(a,b,a+b)

(array([[ 1, -2],
        [ 3,  0]]), array([[ 4, -1],
        [ 0,  5]]), array([[ 5, -3],
        [ 3,  5]]))

$$\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix} \begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}=\begin{pmatrix}
(1*4 + -2*0) & (1*(-1) + -2*5)\\ 
(3*4 + 0*0) & (3*(-1) + 0*5)
\end{pmatrix}=\begin{pmatrix}
4 & -11\\ 
12 & -3
\end{pmatrix}.$$

In [3]:
np.dot(a,b)

array([[  4, -11],
       [ 12,  -3]])

### Задание №3

Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислите линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$

$3A-2B+4C = 3*\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix} - 2*\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix} + 4*\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}=\begin{pmatrix}
3 - 0 + 8 & 21 - 10 -16\\ 
9 -4 +4 & -18 +2 +4
\end{pmatrix}=\begin{pmatrix}
11 & -5\\ 
9 & -12
\end{pmatrix}.$

In [4]:
a=np.array([[1,7],[3,-6]])
b=np.array([[0,5],[2,-1]])
c=np.array([[2,-4],[1,1]])
3*a-2*b+4*c

array([[ 11,  -5],
       [  9, -12]])

### Задание №4

Дана матрица $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.
Вычислите $AA^{T}$ и $A^{T}A$.

$A^{T}=\begin{pmatrix}
4 & 5 & 2\\ 
1 & -2 & 3
\end{pmatrix}$

$AA^{T} = \begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix} \cdot \begin{pmatrix}
4 & 5 & 2\\ 
1 & -2 & 3
\end{pmatrix}  = \begin{pmatrix}
4\cdot4+1\cdot1 & 4\cdot5+1\cdot(-2) & 4\cdot2+1\cdot3\\ 
5\cdot4+(-2)\cdot1 & 5\cdot5+(-2)\cdot(-2) & 5\cdot2+(-2)\cdot3\\ 
2\cdot4+3\cdot1 & 2\cdot5+3\cdot(-2) & 2\cdot2+3\cdot3
\end{pmatrix}=\begin{pmatrix}
17 & 18 & 11\\ 
18 & 29 & 4\\ 
11 & 4 & 13
\end{pmatrix}$

$A^{T}A = \begin{pmatrix}
4 & 5 & 2\\ 
1 & -2 & 3
\end{pmatrix} \cdot \begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix} = \begin{pmatrix}
4\cdot4+5\cdot5+2\cdot2 & 4\cdot1+5\cdot(-2)+2\cdot3\\ 
1\cdot4+(-2)\cdot5+3\cdot2 & 1\cdot1+(-2)\cdot(-2)+3\cdot3
\end{pmatrix}=\begin{pmatrix}
45 & 0\\ 
0 & 14
\end{pmatrix}$

In [5]:
A = np.array([[4,1],[5,-2],[2,3]])
A_t = A.T
(np.dot(A,A_t), np.dot(A_t,A))

(array([[17, 18, 11],
        [18, 29,  4],
        [11,  4, 13]]), array([[45,  0],
        [ 0, 14]]))

### Задание №5*

Напишите на Python функцию для перемножения двух произвольных матриц, не используя NumPy.

In [21]:
def mult(A,B):
  A_shape = A.shape
  B_shape = B.shape
  if A_shape[1]!=B_shape[0]:
    raise ValueError
  result = np.array([[0 for i in range(A_shape[0])] for j in range(B_shape[1])])
  for i in range(A_shape[0]):
    for j in range(B_shape[1]):
      for k in range(A_shape[1]):
        result[i][j]=result[i][j]+A[i][k]*B[k][j]
  return result

(mult(A,A_t), mult(A_t,A))

(array([[17, 18, 11],
        [18, 29,  4],
        [11,  4, 13]]), array([[45,  0],
        [ 0, 14]]))

## Матрицы и матричные операции. Часть 2

### Задание №1

Вычислите определитель:

   a)

$$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix};$$

   б)
    
$$\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix};$$
    
   в)

$$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix}.$$


$$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix} = sinx ⋅ sinx + cosx ⋅ cosx = 1$$

$$\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix} = 4⋅\begin{vmatrix}
5 & 1\\ 
0 & 9
\end{vmatrix} - 2⋅\begin{vmatrix}
0 & 1\\ 
0 & 9
\end{vmatrix} + 3⋅\begin{vmatrix}
0 & 5\\ 
0 & 0
\end{vmatrix} = 4 * 5 * 9 = 180$$

In [7]:
np.linalg.det(np.array([[4,2,3],[0,5,1],[0,0,9]]))

180.0

$$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix} = 1⋅\begin{vmatrix}
5 & 6\\ 
8 & 9
\end{vmatrix} - 2⋅\begin{vmatrix}
4 & 6\\ 
7 & 9
\end{vmatrix} + 3⋅\begin{vmatrix}
4 & 5\\ 
7 & 8
\end{vmatrix} = 5⋅9-6⋅8 - 2⋅(4⋅9-7⋅6)+3⋅(4⋅8-7⋅5) = 45-48-72+84+96-105 = -3+12-9 = 0$$

In [8]:
np.linalg.det(np.array([[1,2,3],[4,5,6],[7,8,9]]))

0.0

### Задание №2

Определитель матрицы $A$ равен $4$. Найдите:

   а) $det(A^{2})$;
    
   б) $det(A^{T})$;
    
   в) $det(2A)$.

а) $det(A^{2}) = det(A)⋅ = det(A) = 16$;
    
   б) $det(A^{T}) = det(A) = 4$;
    
   в) $det(2A) = det(A)⋅det(2) = 8$.

### Задание №3

Докажите, что матрица:

$$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}$$
   
вырожденная.

Матрица квадратная, найдем ее определитель:
$$\begin{vmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{vmatrix} = -2⋅\begin{vmatrix}
-14 & 6\\ 
7 & 13
\end{vmatrix} - 7⋅\begin{vmatrix}
4 & 6\\ 
-3 & 13
\end{vmatrix} - 3⋅\begin{vmatrix}
4 & -14\\ 
-3 & 7
\end{vmatrix} = -2(-14⋅13-6⋅7) - 7⋅(4⋅13+6⋅3)-3⋅(4⋅7-14⋅3) = 448-490+42 = 490-490 = 0.$$
Тк определитель равен нулю и матрица квадратная => матрица вырожденная.

### Задание №4

Найдите ранг матрицы:

   а) $\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix};$

   б) $\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}.$

In [9]:
np.linalg.matrix_rank(np.array([[1,2,3],[1,1,1],[2,3,4]]))

2

In [10]:
np.linalg.matrix_rank(np.array([[0,0,2,1],[0,0,2,2],[0,0,4,3],[2,3,5,6]]))

3